GET http://localhost:2000/product
# send request to get all products

###
GET http://localhost:2000/product/5
# send request to get products by id

### send request to add products
POST  http://localhost:2000/product
Content-Type: application/json

{
    "name": "Primogems",
    "quantity": 300,
    "price": 79000
}

### send request for update products
PATCH  http://localhost:2000/product/1
Content-Type: application/json

{
    "name": "Simp Keqing",
    "quantity": 100,
    "price": 55000
}

### send request for deleted products
DELETE  http://localhost:2000/product/2